### PR TITLE
Alternative to `serviceAccountName changes required for brains to pass`

### PR DESCRIPTION
**Pull request by andreas-kupries**
Ref: https://trello.com/c/8b8F5QCt/767-serviceaccountname-changes-required-for-brains-to-pass

Alternate solution to the service account for brain tests.
First PR is https://github.com/SUSE/scf/pull/1692

This solution pulls the SA and role information for brain tests out of the manifest and into a separate kube config.This config is further extended with a PSP and associated cluster role (binding).

To keep fissile working the brain test SA is set to `default`.

At test time the actual namespace is inserted into the new SA+PSP configuration, and the name of the actual SA from that into the brain config. This is conditional to brain tests. smoke and cats are not edited.

### CODE REVIEW

**Comment by andreas-kupries** [comment]
Sure.

**Comment by f0rmiga** [comment]
@andreas-kupries I think this one is also no longer relevant, right?

**Comment by andreas-kupries** [comment]
Can be closed/deleted

**Comment by f0rmiga** [comment]
Closing as this code is not relevant to what we have on brains.

**Pull request closed without merging**
