### PR TITLE
make all patches idempotent. Fixes #2844

### PR DESCRIPTION
**Pull request by c0d1ngm0nk3y**
## Description

Make patches idempotent, so that the `initContainers` can be run several times without failing.

## Motivation and Context
see https://github.com/SUSE/scf/pull/2845

## How Has This Been Tested?
Installed `scf` via `cf-operator` and checked that all pods are started.

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by phil9909** [comment]
Rebased and added one missing patch we somehow missed before.

**Comment by f0rmiga** [comment]
@c0d1ngm0nk3y Nice! We indeed need this. Could you reopen the PR on SUSE/kubecf, please?

**Comment by c0d1ngm0nk3y** [comment]
> @c0d1ngm0nk3y Nice! We indeed need this. Could you reopen the PR on SUSE/kubecf, please?

Done: https://github.com/SUSE/kubecf/pull/56

**Comment by mook-as** [comment]
Closing; SUSE/kubecf#56 was already merged.  Thanks for bearing with us as the repos get moved around!

**Pull request closed without merging**
